# Generated by Django 3.2 on 2023-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayed_university_app', '0003_alter_acronyms_long_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acronyms',
            name='long_form',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
